kind: pipeline
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/drone-track-repository
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      tag:
        - latest
