kind: pipeline
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: lint
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile
      - yarn lint

  - name: build
    image: node:current-alpine
    commands:
      - yarn build

  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/drone-track-repository
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest
