loglevel: PLUGIN_LOG_LEVEL

git-username: PLUGIN_GIT_USERNAME
git-password: PLUGIN_GIT_PASSWORD

api-url: PLUGIN_API_URL
this-repo: PLUGIN_THIS_REPO
track-repo: PLUGIN_TRACK_REPO

release-file: PLUGIN_RELEASE_FILE
environment-variable: PLUGIN_ENV_VAR

do-tag: PLUGIN_DO_TAG
do-release: PLUGIN_DO_RELEASE
